/*
 * GENERATED by scripts/generate-tokens.mjs — do not edit.
 *
 * Source: ../mobile/constants/theme.ts
 * Regenerate: npm run tokens
 */


/** The app's light palette, for the handful of places a value has to reach JavaScript. */
export const lightColors = {
  "kiwi": "#A3E635",
  "kiwiDeep": "#4D7C0F",
  "kiwiTint": "#EEFBD6",
  "grape": "#7C5CFF",
  "grapeDeep": "#5B3FD9",
  "grapeTint": "#EDE9FF",
  "coral": "#FF6B4A",
  "coralDeep": "#D93C1B",
  "coralTint": "#FFEBE5",
  "sky": "#38BDF8",
  "skyDeep": "#0369A1",
  "skyTint": "#E2F5FE",
  "sun": "#FFD447",
  "sunDeep": "#A16207",
  "sunTint": "#FFF6DA",
  "background": "#FBFBF4",
  "surface": "#FFFFFF",
  "surfaceSunken": "#F3F4EA",
  "surfaceInverse": "#0B0F0A",
  "ink": "#0B0F0A",
  "inkMuted": "#5A6155",
  "inkFaint": "#8A9283",
  "inkInverse": "#FBFBF4",
  "hairline": "#E8E9DE",
  "hairlineStrong": "#D5D7C8",
  "trackKiwi": "#E4F3C8",
  "trackGrape": "#E5E0FB",
  "trackCoral": "#FBE0D8",
  "ringPromiseFrom": "#7FC117",
  "ringPromiseTo": "#C3F45E",
  "ringGoalFrom": "#6A48F0",
  "ringGoalTo": "#AE96FF",
  "ringCircleFrom": "#F5502B",
  "ringCircleTo": "#FFA07A",
  "shadow": "#2A3018"
} as const;

/** The app's dark palette. Used by the home-screen widget demo.  */
export const darkColors = {
  "kiwi": "#B8F04A",
  "kiwiDeep": "#D2F97F",
  "kiwiTint": "#1E2A10",
  "grape": "#9B7DFF",
  "grapeDeep": "#BCA8FF",
  "grapeTint": "#211B3A",
  "coral": "#FF8566",
  "coralDeep": "#FFA992",
  "coralTint": "#2E1810",
  "sky": "#56CCFA",
  "skyDeep": "#8FDDFC",
  "skyTint": "#0F2430",
  "sun": "#FFDE6B",
  "sunDeep": "#FFEBA0",
  "sunTint": "#2B2310",
  "background": "#0C0F0A",
  "surface": "#161A12",
  "surfaceSunken": "#10140D",
  "surfaceInverse": "#FBFBF4",
  "ink": "#F5F7F0",
  "inkMuted": "#A3AC9A",
  "inkFaint": "#6F7A66",
  "inkInverse": "#0B0F0A",
  "hairline": "#242A1D",
  "hairlineStrong": "#333A29",
  "trackKiwi": "#26380F",
  "trackGrape": "#251B52",
  "trackCoral": "#3E1A0D",
  "ringPromiseFrom": "#8FD41F",
  "ringPromiseTo": "#D2F97F",
  "ringGoalFrom": "#7E5CFF",
  "ringGoalTo": "#BCA8FF",
  "ringCircleFrom": "#FF6B45",
  "ringCircleTo": "#FFB496",
  "shadow": "#000000"
} as const;

/** Font family names as the app declares them, for reference — the site loads variable
 *  equivalents through `next/font`, so these are documentation, not `font-family` values. */
export const appFonts = {
  "display": "Sora_800ExtraBold",
  "displayBold": "Sora_700Bold",
  "displaySemibold": "Sora_600SemiBold",
  "displayMedium": "Sora_500Medium",
  "regular": "Inter_400Regular",
  "medium": "Inter_500Medium",
  "semibold": "Inter_600SemiBold",
  "bold": "Inter_700Bold",
  "mono": "JetBrainsMono_500Medium",
  "monoSemibold": "JetBrainsMono_600SemiBold"
} as const;

export type ColorName = keyof typeof lightColors;
