/**
 * Generates the site's design tokens from the app's.
 *
 * `mobile/constants/theme.ts` is the source of truth for KEPT's colour, type, spacing and
 * motion. Copying those hexes into CSS by hand is how a marketing site ends up a shade off
 * the product it is selling, so this imports the module directly and emits both a stylesheet
 * and a typed module from it. Add a colour to the app and it appears here on the next build.
 *
 * The import works because `theme.ts` is pure data — no React Native, no imports at all — so
 * Node's type stripping can load it as-is. If someone ever adds an import to that file this
 * script is what will break, loudly, which is the right place for it to break.
 *
 * Both outputs are committed. That keeps `web/` buildable on its own, and it makes a palette
 * change to the app show up as a reviewable diff here rather than silently at deploy time.
 */

import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const SOURCE = join(root, '..', 'mobile', 'constants', 'theme.ts')

const theme = await import(SOURCE)
const { lightColors, darkColors, fonts, type, space, radii, elevation, motion } = theme

/** `kiwiDeep` → `kiwi-deep`, `1` → `1`. */
const kebab = (key) =>
  String(key)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase()

/**
 * The app stores spacing and radii as bare numbers — React Native has no units — so every one
 * of them has to be given `px` on the way out. Emitting `--space-7: 28` is not a CSS error
 * that anything reports: the declaration is simply dropped, the property falls back to its
 * initial value, and you get a button with no padding and a "pill" with square corners. Which
 * is exactly what happened the first time this ran.
 */
const declare = (prefix, entries, unit = '') =>
  Object.entries(entries).map(
    ([key, value]) => `  --${prefix}${kebab(key)}: ${value}${typeof value === 'number' ? unit : ''};`,
  )

const banner = `/*\n * GENERATED by scripts/generate-tokens.mjs — do not edit.\n *\n * Source: ${relative(root, SOURCE)}\n * Regenerate: npm run tokens\n */\n`

/*
 * Light is the page. Dark is scoped to `[data-theme="dark"]` rather than bound to
 * `prefers-color-scheme`, because the dark palette here is a *component* state — the
 * home-screen widget demo flips it — not a site-wide preference we have designed for yet.
 * Wiring it to the media query would hand half the readers a page nobody has laid out.
 */
const css = [
  banner,
  ':root {',
  '  /* Colour — light */',
  ...declare('', lightColors),
  '',
  "  /* Type — the app's scale, in rem, from a 16px root */",
  ...Object.entries(type).flatMap(([name, style]) => [
    `  --text-${kebab(name)}-size: ${style.fontSize / 16}rem;`,
    `  --text-${kebab(name)}-height: ${style.lineHeight / 16}rem;`,
    ...(style.letterSpacing === undefined
      ? []
      : [`  --text-${kebab(name)}-tracking: ${style.letterSpacing / 16}rem;`]),
  ]),
  '',
  "  /* Spacing — the app's 4pt grid */",
  ...declare('space-', space, 'px'),
  '',
  '  /* Radii */',
  ...declare('radius-', radii, 'px'),
  '',
  '  /* Motion — durations in ms, as seconds for CSS */',
  `  --motion-state: ${motion.state}ms;`,
  `  --motion-entrance: ${motion.entrance}ms;`,
  '',
  "  /* Elevation — the app's ambient shadows, translated to box-shadow */",
  ...Object.entries(elevation).map(([name, value]) => {
    const { shadowOffset, shadowRadius, shadowOpacity } = value
    return `  --shadow-${kebab(name)}: ${shadowOffset.width}px ${shadowOffset.height}px ${shadowRadius}px color-mix(in srgb, var(--shadow) ${Math.round(shadowOpacity * 100)}%, transparent);`
  }),
  '}',
  '',
  '[data-theme="dark"] {',
  ...declare('', darkColors),
  '}',
  '',
].join('\n')

const ts = [
  banner,
  '',
  "/** The app's light palette, for the handful of places a value has to reach JavaScript. */",
  `export const lightColors = ${JSON.stringify(lightColors, null, 2)} as const;`,
  '',
  "/** The app's dark palette. Used by the home-screen widget demo.  */",
  `export const darkColors = ${JSON.stringify(darkColors, null, 2)} as const;`,
  '',
  '/** Font family names as the app declares them, for reference — the site loads variable',
  ' *  equivalents through `next/font`, so these are documentation, not `font-family` values. */',
  `export const appFonts = ${JSON.stringify(fonts, null, 2)} as const;`,
  '',
  'export type ColorName = keyof typeof lightColors;',
  '',
].join('\n')

/*
 * A unitless length is a declaration the browser throws away in silence — no console warning,
 * no build error, just a property quietly back at its initial value. That is a bad failure
 * mode for a file nobody reads, so it fails here instead.
 *
 * `0` and `--progress`-style ratios are legitimately unitless; nothing in this file emits one
 * yet, so anything bare is a mistake.
 */
const unitless = css
  .split('\n')
  .map((line) => line.match(/^\s*(--[\w-]+):\s*(-?\d*\.?\d+)\s*;/))
  .filter((match) => match && match[2] !== '0')

if (unitless.length) {
  throw new Error(
    `Unitless length(s) in generated CSS — the browser will drop these declarations:\n` +
      unitless.map((m) => `  ${m[1]}: ${m[2]}`).join('\n'),
  )
}

await writeFile(join(root, 'app', 'tokens.css'), css, 'utf8')
await writeFile(join(root, 'lib', 'tokens.generated.ts'), ts, 'utf8')

console.log(
  `tokens: ${Object.keys(lightColors).length} colours, ${Object.keys(type).length} type styles → app/tokens.css, lib/tokens.generated.ts`,
)
